spring:
  datasource:
    url: jdbc:mysql://localhost:3306/PRACTICEDB?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ict
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8085