spring:
  datasource:
    url: jdbc:mariadb://localhost:23306/PRACTICEDB
    username: root
    password: rhyme4109!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8085