spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mariadb://first-machine-db.c3u6uwaq4c7b.ap-northeast-2.rds.amazonaws.com:23306/PRACTICEDB
    username: root
    password: rhyme4109!
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8085